### ISSUE TITLE
[Words/Colors and Shapes] The word "куб" sounds very quiet (Exercises 11, 22, 24, 33, 44)

### ISSUE THREAD

**Issue by NatalyChernovaQA** [Brain-up/brn#1513]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words / Colors and Shapes.
Exercise 11: http://31.184.253.199/groups/2/series/1/subgroup/10/exercise/316/task/316
Exercise 22: http://31.184.253.199/groups/2/series/1/subgroup/10/exercise/327/task/327
Exercise 24: http://31.184.253.199/groups/2/series/1/subgroup/10/exercise/329/task/329
Exercise 33: http://31.184.253.199/groups/2/series/1/subgroup/10/exercise/338/task/338
Exercise 44: http://31.184.253.199/groups/2/series/1/subgroup/10/exercise/349/task/349
Steps:
1. Select exercise 11.
2. Click the play button.
Actual Result: The word "куб" sounds quieter than other words.
Expected Result: All words sound the same loud.

**Comment by SFin-tech** [comment]
corrected
