### ISSUE TITLE
[Words/At school] In the "At School/+ voices" section, there are no voices in exercises 15-17

### ISSUE THREAD

**Issue by NatalyChernovaQA** [Brain-up/brn#1515]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words / At school / At school + voices.
Еxercise 15: http://31.184.253.199/groups/2/series/1/subgroup/15/exercise/471/task/471
Еxercise 16: http://31.184.253.199/groups/2/series/1/subgroup/5/exercise/175/task/175
Еxercise 17: http://31.184.253.199/groups/2/series/1/subgroup/5/exercise/176/task/176
Steps:
1. Select exercise 15.
2. Click play.
Actual Result: Words are played without additional voices.
Expected Result: Words are played with additional voices.

**Comment by SFin-tech** [comment]
not fixed yet

**Comment by koylubaevnt** [comment]
Couldn't reproduce.
I suppose it was fixed.
