### ISSUE TITLE
[Words/any section] When interrupting the 'listen' mode, in the 'solve' mode, the first word is either not pronounced or pronounced incompletely

### ISSUE THREAD

**Issue by NatalyChernovaQA** [Brain-up/brn#1516]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words / any section (for example, "in the hospital).
Steps:
1. Select exercise 1.
2. Press "play".
3. Press "repeat" and "solve".
Actual Result: The first word is either not pronounced or not pronounced completely.
Expected Result: All words are pronounced completely and clearly.

**Comment by SFin-tech** [comment]
corrected
