### ISSUE TITLE
[Home page/the avatar does not change] The avatar image can't change on the home page

### ISSUE THREAD

**Issue by Alleksandravd** [Brain-up/brn#1546]
Precondition:
Log in with an existing user. Open home page. 
Steps:                    
1.Press the avatar image
2. Choose another picture. 
Actual Result: The picture of the avatar has not changed
Expected Result: The picture of the avatar changed to the selected one

**Comment by SFin-tech** [comment]
not fixed yet

**Comment by koylubaevnt** [comment]
Request and response from backend service is correct. 
Need make change in Frontend -> update avatar in profile and in tabbar

**Comment by HappyEgoiste** [comment]
As of Jan 18, 2023 not fixed, avatar only changes when getting back to the previous or new pages

**Comment by HappyEgoiste** [comment]
QA verified
