### ISSUE TITLE
[words/weather] The exercise 14 is not marked as an active exercise

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1611]
Preconditions:
1 Log in as an existing user.  Opened:groups/speech exercises/words/weather
http://brainup.site/groups/2/series/1/subgroup/14

Step:
1 Execute  the first 13 exercises

Actuai result: The exercise 14 is not marked as an active exircise, the exercise 13 is not marked done
Expected result:The exercise 14 is marked as an active exircise, the exercise 13 is marked done

![chrome_DX1sNnSnXA](https://user-images.githubusercontent.com/79014501/109420788-4b232c00-79e5-11eb-81c6-f9de7df3d9c2.png)

**Comment by koylubaevnt** [comment]
Couldn't reproduce.
I suppose it was fix.
