### ISSUE TITLE
[Words/Family] hen solving the exercise, the matrix of words is distorted.the problem is in the word "Новорожденный"

### ISSUE THREAD

**Issue by Acya8** [Brain-up/brn#1613]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words / Family.
http://31.184.253.199/groups/2/series/1/subgroup/1/exercise/14/task/14

Steps:
1. Select exercise 14.
2. Repeat the word "Новорожденный"
     Actual result: the matrix of words moves out when the word "Новорожденный" is pressed. Buttons go below. the word "Новорождённый" is not spoken 
     Expected Result: a matrix of words in place. When you click on a word "Новорождённый", it is pronounced

3. Click to solve
     Actual result: the word "Новорождённый" is not selected(or selected after repeated pressing on the word). the matrix of words moves out when the word newborn is pressed. Buttons go below. 
       Expected Result: the word newborn is chosen

**Comment by SFin-tech** [comment]
corrected
