### ISSUE TITLE
[Words/Family] Exercises 15, 16 ,17. No noise

### ISSUE THREAD

**Issue by Acya8** [Brain-up/brn#1614]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words / Family.
http://31.184.253.199/groups/2/series/1/subgroup/1/exercise/15/task/15
Steps:
1. Select exercise 15(16/17).
2. Press listen / repeat / solve
     Actual result: No noise 
    Expected Result: There is noise

**Comment by SFin-tech** [comment]
not fixed yet

**Comment by ViacheslavFin** [comment]
not fixed
Actual result: No noise
Expected Result: There is noise

**Comment by koylubaevnt** [comment]
@ViacheslavFin wich browser do you use?
Because on Firefox is all OK.

**Comment by ViacheslavFin** [comment]
@koylubaevnt  Chrome

**Comment by ElenaSpb** [comment]
fixed

**Comment by ViacheslavFin** [comment]
@ElenaSpb, hi. 
Corrected

**Comment by YuryHerasimau** [comment]
Checked the bug-fix. Works fine
Tested on: Chrome v. 108.0.5359.71, Firefox v. 107.0.1

Closing ticket
