### ISSUE TITLE
[Words/Family] Exercises 28. the problem is in the word "Новорожденный"

### ISSUE THREAD

**Issue by Acya8** [Brain-up/brn#1615]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words / Family.
http://31.184.253.199/groups/2/series/1/subgroup/1/exercise/28/task/28

Steps:

1.Select exercise 28.

2.Repeat the word "Новорожденный"
      Actual result: the matrix of words moves out when the word "Новорожденный" is pressed. Buttons go below. the word "Новорожденный" is not spoken
      Expected Result: a matrix of words in place. When you click on a word "Новорожденный", it is pronounced

3.Click to solve
    Actual result: the word "Новорожденный" is not selected(or selected after repeated pressing on the word). the matrix of words moves out when the word newborn is pressed. Buttons go below.
    Expected Result: the word newborn is chosen

**Comment by SFin-tech** [comment]
corrected
