### ISSUE TITLE
[Words / What I eat] Exercises 12. Wrong stress in a word "Ужинаю"

### ISSUE THREAD

**Issue by Acya8** [Brain-up/brn#1616]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words / What I eat.
http://31.184.253.199/groups/2/series/1/subgroup/3/exercise/96/task/96
http://31.184.253.199/groups/2/series/1/subgroup/3/exercise/110/task/110

Steps:

1.Select exercise 12/26.
2. Click listen/repeat /solve word "Ужинаю"
    Actual result:  ужина́ю — если образовано от слова ужинать (сжинать)
   Expected Result:  у́жинаю — если образовано от слова ужинать (есть ужин)

**Comment by SFin-tech** [comment]
fixed
