### ISSUE TITLE
[Words/What I eat] Exercises 15, 16 ,17. No noise

### ISSUE THREAD

**Issue by Acya8** [Brain-up/brn#1617]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words / What I eat.
http://31.184.253.199/groups/2/series/1/subgroup/3/exercise/99/task/99
Steps:

1.Select exercise 15(16/17).
2.Press listen / repeat / solve
     Actual result: No noise
     Expected Result: There is noise

**Comment by Micirin** [comment]
pass

**Comment by Micirin** [comment]
done

**Comment by SFin-tech** [comment]
not fixed yet

**Comment by koylubaevnt** [comment]
@SFin-tech  wich browser do you use?
Because on Firefox is all OK.

**Comment by ElenaSpb** [comment]
fixed

**Comment by ViacheslavFin** [comment]
@ElenaSpb, @koylubaevnt, corrected on Chrome

**Comment by YuryHerasimau** [comment]
Checked the bug-fix. Works fine
Tested on: Chrome v. 108.0.5359.71, Firefox v. 107.0.1

Closing ticket
