### ISSUE TITLE
[Words/Animal world] Exercise 14. Is in a block with noise

### ISSUE THREAD

**Issue by Acya8** [Brain-up/brn#1618]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words / Animal world.
http://31.184.253.199/groups/2/series/1/subgroup/8

Steps:

1.Open Words/Animal world
  Actual result: Exercise 14 is in a block with noise 
   Expected Result: Exercise 14 is in a block without noise

**Comment by Micirin** [comment]
done

**Comment by SFin-tech** [comment]
corrected
