### ISSUE TITLE
[Words / Pets] Exercises 12,23. Wrong stress in a word "Шиншила"

### ISSUE THREAD

**Issue by dmitiikor** [Brain-up/brn#1628]
Precondition: 
Log in with an existing user. 
Open: Groups / Speech exercises / Words / Pets.
http://brainup.site/groups/2/series/1/subgroup/7/exercise/242/task/242
http://brainup.site/groups/2/series/1/subgroup/7/exercise/253/task/253
Steps:
1. Select exercise 12/23.
 2. Click listen/repeat /solve word "Шиншила"
 Actual result: ши́ншилла 
 Expected Result: шинши́ла

**Comment by Micirin** [comment]
fail
