### ISSUE TITLE
Tasks Matrix issues

### ISSUE THREAD

**Issue by lifeart** [Brain-up/brn#1638]
- [x] #1628 
- [x] #1632
- [x] #1618
- [x] #1615
- [x] #1613
- [x] #1610
- [x] #1609
- [x] #1608
- [x] #1607 
- [x] #1606 
- [x] #1605 
- [x] #1604 
- [x] #1603 
- [x] #1602 
- [x] #1601 
- [x] #1600
- [x] #1598
- [x] #1597 
- [x] #1596 
- [x] #1595 
- [x] #1594
- [x] #1574 
- [x] #1633

**Comment by dmitiikor** [comment]
- [ ] #1633

**Comment by SFin-tech** [comment]
done
