### ISSUE TITLE
[words] "Pause" button does not work in the mode "listen" for all exercises

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1663]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/words
https://brainup.site/groups/2/series/1

Step:
1 Select "family", exercise 1, for example
2 Press the red button
3 Press "Pause"

Actuai result: the words continue to be voiced
Expected result: the words are not voiced

**Comment by lifeart** [comment]
@SiamionavaV `pause` button not supposed to pause audio, it pauses timer
