### ISSUE TITLE
[Words / Transport] Exercises 13,24. Wrong stress in a word "Пристань"]

### ISSUE THREAD

**Issue by Alleksandravd** [Brain-up/brn#1681]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words / Transport.
http://brainup.site/groups/2/series/1/subgroup/9/exercise/293/task/293
http://brainup.site/groups/2/series/1/subgroup/9/exercise/304/task/304
 
Steps:
1.Select exercise 13/24.
2. Click listen/repeat /solve word "Пристань"
Actual result: пристань — ударение на а
Expected Result: пристань — ударение на и

**Comment by Micirin** [comment]
fail

**Comment by SFin-tech** [comment]
corrected
