### ISSUE TITLE
[Words / Favorite home] Exercise 1,15,29,43. Extraneous sound when pronouncing a word "Дом"]

### ISSUE THREAD

**Issue by Alleksandravd** [Brain-up/brn#1682]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words / Favorite home
http://brainup.site/groups/2/series/1/subgroup/2/exercise/29/task/29 
https://brainup.site/groups/2/series/1/subgroup/2/exercise/43/task/43
https://brainup.site/groups/2/series/1/subgroup/2/exercise/57/task/57
https://brainup.site/groups/2/series/1/subgroup/2/exercise/71/task/71
 
Steps:
1.Select exercise 1/15/29/43
2. Repeat the word "Дом"
Actual result: the word is pronounced with an extraneous click
Expected Result: the word is pronounced without extraneous sounds

**Comment by Micirin** [comment]
done

**Comment by SFin-tech** [comment]
corrected
