### ISSUE TITLE
[Words / Favorite home] Exercise 9,23,37,51. Extraneous sound when pronouncing a word "Телевизор"]

### ISSUE THREAD

**Issue by Alleksandravd** [Brain-up/brn#1683]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words / Favorite home
http://brainup.site/groups/2/series/1/subgroup/2/exercise/37/task/37 
https://brainup.site/groups/2/series/1/subgroup/2/exercise/51/task/51
https://brainup.site/groups/2/series/1/subgroup/2/exercise/65/task/65
https://brainup.site/groups/2/series/1/subgroup/2/exercise/79/task/79
Steps:
1.Select exercise 9/23/37/51
2. Repeat the word "Телевизор"
Actual result: the word is pronounced with an extraneous click
Expected Result: the word is pronounced without extraneous sounds

**Comment by Micirin** [comment]
done

**Comment by SFin-tech** [comment]
corrected
