### ISSUE TITLE
[Home page] The sign 'comma' is not specified in the sentence

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1691]
Steps
1 Open https://brainup.site/
Actual result: 
![chrome_Iqw0PvxFul](https://user-images.githubusercontent.com/79014501/110648755-0c058f80-81ca-11eb-967b-9abed8acd878.png)

Expected Result:  Наш сайт - это платформа интерактивных упражнений для взрослых и детей от семи лет с когнитивными проблемами восприятия речи, которая помогает тренировать способности слушать и понимать

**Comment by Micirin** [comment]
done

**Comment by SFin-tech** [comment]
corrected
