### ISSUE TITLE
[sentences/a 2-words sentence] In the exercise 14 in the mode "listen"  the word "убегает" is not voiced

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1697]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 2-words sentence/14 exercise
https://brainup.site/groups/2/series/4/subgroup/29/exercise/1190/task/1182
2 The first 13 exercises are completed

Step:

 Press the red button

Actuai result: the word "убегает" is not voiced
Expected result: all words are voiced

**Comment by Micirin** [comment]
https://brainup.site/groups/2/series/4/subgroup/55/exercise/1637/task/1625 
done

**Comment by SFin-tech** [comment]
corrected
