### ISSUE TITLE
[sentences/a 2-words sentence] In the exercise 15 in the mode "listen" the word "побеждает" is not voiced

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1698]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 2-words sentence/15 exercise
https://brainup.site/groups/2/series/4/subgroup/29/exercise/1191/task/1183
2 The first 14 exercises are completed

Step:
Press the red button

Actuai result: the word "побеждает" is not voiced
Expected result: all words are voiced

**Comment by Micirin** [comment]
https://brainup.site/groups/2/series/4/subgroup/55/exercise/1638/task/1626
done

**Comment by Micirin** [comment]
In exercise 18 the word "машина" was not found

**Comment by SFin-tech** [comment]
corrected
