### ISSUE TITLE
[sentences/a 2-words sentence]  Periodically wrong stress in a word "Машина" in the exercise 18 in the mode "solve"

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1699]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 2-words sentence/18 exercise
https://brainup.site/groups/2/series/4/subgroup/29/exercise/1194/task/1186
2 The first 17 exercises are completed

Step:

Press the red button
Select the mode "solve"

Actuai result: ма́шина 
Expected result: маши́на

**Comment by SFin-tech** [comment]
corrected
