### ISSUE TITLE
sentences/a 2-words sentence] In the exercise 20 in the mode "listen" the word "провожает" is not voiced

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1700]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 2-words sentence/20 exercise
https://brainup.site/groups/2/series/4/subgroup/29/exercise/1196/task/1188
2 The first 19 exercises are completed

Step:

Press the red button

Actuai result: the word "провожает" is not voiced
Expected result: all words are voiced

**Comment by Micirin** [comment]
https://brainup.site/groups/2/series/4/subgroup/55/exercise/1643/task/1631
done

**Comment by SFin-tech** [comment]
corrected
