### ISSUE TITLE
sentences/a 2-words sentence] In the exercise 21 in the mode "listen" the word "сидит" is not voiced 

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1701]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 2-words sentence/21 exercise
https://brainup.site/groups/2/series/4/subgroup/29/exercise/1197/task/1189
2 The first 20 exercises are completed

Step:

Press the red button

Actuai result: the word "сидит" is not voiced
Expected result: all words are voiced

**Comment by Micirin** [comment]
https://brainup.site/groups/2/series/4/subgroup/55/exercise/1644/task/1632
done

**Comment by koylubaevnt** [comment]
Couldn't reproduce.
I suppose it was fix.
