### ISSUE TITLE
[sentences/a 2-words sentence] Wrong stress in a word "Мелет" in the exercise 29

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1702]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 2-words sentence/29 exercise
https://brainup.site/groups/2/series/4/subgroup/29/exercise/1205/task/1197
2 The first 28 exercises are completed

Step:

Press the red button

Actuai result: меле́т 
Expected result: ме́лет

**Comment by Micirin** [comment]
https://brainup.site/groups/2/series/4/subgroup/55/exercise/1652/task/1640
word "мелет" was not found, but wrong stress in a word "доит"
fail

**Comment by SFin-tech** [comment]
corrected
