### ISSUE TITLE
sentences/a 2-words sentence] In the exercise 30 in the mode "listen" the word "едет" is not voiced

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1705]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 2-words sentence/30 exercise
https://brainup.site/groups/2/series/4/subgroup/29/exercise/1206/task/1198
2 The first 29 exercises are completed

Step:

Press the red button

Actuai result: the word "едет" is not voiced
Expected result: all words are voiced

**Comment by Micirin** [comment]
https://brainup.site/groups/2/series/4/subgroup/55/exercise/1653/task/1641
done

**Comment by SFin-tech** [comment]
corrected
