### ISSUE TITLE
sentences/a 2-words sentence] In the exercise 35  a word "торжествует"  is written with a mistake

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1706]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 2-words sentence/35 exercise
https://brainup.site/groups/2/series/4/subgroup/29/exercise/1211/task/1203
2 The first 34 exercises are completed

Step:

Press the red button

Actuai result: the word "торжествет"
![chrome_O8Kq7TcWAD](https://user-images.githubusercontent.com/79014501/110952871-bfe85580-8357-11eb-8b39-51140094c8f6.png)

Expected result: the word "торжествует"

**Comment by SFin-tech** [comment]
corrected
