### ISSUE TITLE
[Words/Favorite Home] Invalid download page

### ISSUE THREAD

**Issue by Alleksandravd** [Brain-up/brn#1707]
Precondition:
Log in with an existing user. Open: Groups / Speech exercises / Words /
https://brainup.site/groups/2/series/1

Steps:
Open Words/Favorite home world

Actual result: First, the speech exercises are loaded. Then it goes to the selected group of words.
Expected Result: The selected group of words is loaded

**Comment by DmitriyKoshelev** [comment]
Не понял суть бага ,но все ОК.

**Comment by SFin-tech** [comment]
corrected
