### ISSUE TITLE
[sentences/a 4-words sentence/a 4-words from 12] In the exercise 24 in the mode "listen" the words "шуршит", "пятью", "пакетами" are not voiced

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1709]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 4-words sentence/a 4-words from 12/24 exercise
https://brainup.site/groups/2/series/4/subgroup/31/exercise/1332/task/1324
2 The first 23 exercises are completed

Step:

Press the red button

Actuai result: the words "шуршит", "пятью", "пакетами" are not voiced
Expected result: all words are voiced

**Comment by SFin-tech** [comment]
corrected
