### ISSUE TITLE
[sentences/a 4-words sentence/a 4-words from 12] Wrong stress in a word "пятью" in the exercise 24 in the mode "repeat"

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1710]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 4-words sentence/a 4-words from 12/24 exercise
https://brainup.site/groups/2/series/4/subgroup/31/exercise/1332/task/1324
2 The first 23 exercises are completed

Step:

1. Press the red button
2. Select a word "пятью" in the mode "repeat"

Actuai result: пя́тью
Expected result: пятью́

**Comment by SFin-tech** [comment]
not fixed
