### ISSUE TITLE
[sentences/a 4-words sentence/a 4-words from 12] In the exercise 26 in the mode "listen" the words "чистят", "семнадцать", "кружек" are not voiced

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1712]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 4-words sentence/a 4-words from 12/26 exercise
https://brainup.site/groups/2/series/4/subgroup/31/exercise/1334/task/1326
2 The first 25 exercises are completed

Step:

Press the red button

Actuai result: the words "чистят", "семнадцать", "кружек" are not voiced
Expected result: all words are voiced

**Comment by SFin-tech** [comment]
fixed
