### ISSUE TITLE
[sentences/a 4-words sentence/a 4-words from 16] The exercise 36 is not marked as an active exercise 

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1722]
Preconditions:
1 Log in as an existing user. Opened:Open: groups/speech exercises/sentences/a 4-words sentence/a 4-words from 16
https://brainup.site/groups/2/series/4/subgroup/31

Step:
1 Execute 34, 35 exercises

Actuai result: The exercise 36 is not marked as an active exircise
![chrome_PM5pL6iBg6](https://user-images.githubusercontent.com/79014501/111171872-616ce280-85b6-11eb-97a9-8b4c3a9ee60d.png)

Expected result:The exercise 36 is marked as an active exircise

**Comment by SFin-tech** [comment]
fixed
