### ISSUE TITLE
[sentences/a 4-words sentence/a 4-words from 16]  An  extraneous sound when pronouncing a word "волос" in the exercise 44

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1727]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 4-words sentence/a 4-words from 16/ 44 exercise
https://brainup.site/groups/2/series/4/subgroup/31/exercise/1352/task/1344
2 The first 43 exercises are completed

Step:

Press the red button

Actuai result: the word "волос" has an extraneous sound
Expected result: the word "волос" has not  an extraneous sound

**Comment by SFin-tech** [comment]
fixed
