### ISSUE TITLE
[Non-speech exercises/Signal Frequency] The label is transferred at the moment of clicking on the button [120 ms, 1500 MHz].

### ISSUE THREAD

**Issue by NatalyChernovaQA** [Brain-up/brn#1728]
Precondition:
Предварительное условие:
Log in with an existing user. Open: Groups / Non-Speech Exercises / Signal Frequency.
https://brainup.site/groups/1/series/7/subgroup/41/exercise/1173/task/signal-task-12
Steps:
1. Select exercise 1.
2. Press "play".
3. Select the "repeat" mode.
4. Press the button "[120 ms, 1500 Mhz]".

Actual result: The label is transferred at the moment of clicking on the button [120 ms, 1500 MHz].
Expected Result: The label remains unchanged.

**Comment by NatalyChernovaQA** [comment]
![Untitled](https://user-images.githubusercontent.com/78919128/111308144-617aea00-866b-11eb-9deb-c4dd76e4aa8f.png)

**Comment by SFin-tech** [comment]
fixed
