### ISSUE TITLE
[Words / What I feel] UI. General view of the exercises. The word matrix is broken.

### ISSUE THREAD

**Issue by NatalyChernovaQA** [Brain-up/brn#1732]
Precondition:
Log in with an existing user. Open: Groups / Speech Exercises / Words / What I feel.
Steps:
1. Select exercise 7 (for example).
Actual result: The word matrix is shifted.
Expected Result: The word matrix is not shifted.

Exercise 7: https://brainup.site/groups/2/series/1/subgroup/20/exercise/608/task/608
Exercise 10: https://brainup.site/groups/2/series/1/subgroup/20/exercise/611/task/611
Exercise 13: https://brainup.site/groups/2/series/1/subgroup/20/exercise/614/task/614
Exercise 18: https://brainup.site/groups/2/series/1/subgroup/20/exercise/619/task/619
Exercise 21: https://brainup.site/groups/2/series/1/subgroup/20/exercise/622/task/622
Exercise 24: https://brainup.site/groups/2/series/1/subgroup/20/exercise/625/task/625
Exercise 29: https://brainup.site/groups/2/series/1/subgroup/20/exercise/630/task/630
Exercise 32: https://brainup.site/groups/2/series/1/subgroup/20/exercise/633/task/633
Exercise 35: https://brainup.site/groups/2/series/1/subgroup/20/exercise/636/task/636
Exercise 41: https://brainup.site/groups/2/series/1/subgroup/20/exercise/641/task/641
Exercise 43: https://brainup.site/groups/2/series/1/subgroup/20/exercise/644/task/644
Exercise 46: https://brainup.site/groups/2/series/1/subgroup/20/exercise/647/task/647

**Comment by NatalyChernovaQA** [comment]
![матрица](https://user-images.githubusercontent.com/78919128/111443868-de18d180-871a-11eb-93e7-a7f4ace2c18d.png)

**Comment by lifeart** [comment]
fixed, should be retested

**Comment by SFin-tech** [comment]
fixed
