### ISSUE TITLE
[sentences/a 4-words sentence/a 4-words from 16] Wrong stress in a word "чертит" in the exercises 45, 46

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1737]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 4-words sentence/a 4-words from 16/45 (46) exercise
https://brainup.site/groups/2/series/4/subgroup/31/exercise/1353/task/1345
https://brainup.site/groups/2/series/4/subgroup/31/exercise/1354/task/1346

Step:

Press the red button

Actuai result: черти́т
Expected result: че́ртит

**Comment by SFin-tech** [comment]
Corrected
