### ISSUE TITLE
[a group of words/a 2-words from 6] In the exercise 14 in the mode "listen" the word "убегает" is not voiced

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1748]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/a group of words/a 2-words from 6/14 exercise
https://brainup.site/groups/2/series/3/subgroup/21/exercise/662/task/662
2 The first 13 exercises are completed

Step:

Press the red button

Actuai result: the word  "убегает" is not voiced
Expected result: all words are voiced

**Comment by SFin-tech** [comment]
Corrected
