### ISSUE TITLE
[a group of words/a 2-words from 6] In the exercise 20 in the mode "listen" the word "провожает" is not voiced

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1751]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/a group of words/a 2-words from 6/20 exercise
https://brainup.site/groups/2/series/3/subgroup/21
2 The first 19 exercises are completed

Step:

Press the red button

Actuai result: the word "провожает" is not voiced
Expected result: all words are voiced

**Comment by SFin-tech** [comment]
Corrected
