### ISSUE TITLE
[Sentences/group of words/3 words out of 6] Wrong stress in a word "лисы" in the exercises 17

### ISSUE THREAD

**Issue by NatalyChernovaQA** [Brain-up/brn#1869]
Precondition:
Log in with an existing user. Open: Sentences/group of words/3 words out of 6. 16 exercises were completed.
https://brainup.site/groups/2/series/3/subgroup/22/exercise/726/task/726 
Steps:
1. Select exercise 17.
2. Press "play".
3. Press "repeat".
4. Press "три" + "лисы".
Actual Result: In the phrase "три лисы", the stress in the word "лисы" falls on the letter "И".
Expected Result: In the phrase "три лисы", the stress in the word "лисы" falls on the letter "Ы".

![17 ударение лИсы](https://user-images.githubusercontent.com/78919128/115922141-3020e580-a485-11eb-9769-11368884edeb.jpg)

**Comment by SFin-tech** [comment]
1. A separate word "лисы" stress should fall on "И". I'm sure it's correct.
2. But for the phrase "три лисы" the emphasis should fall on "Ы". In this case, a separate compilation of the process and speech accompaniment is necessary.
