### ISSUE TITLE
[Sentences/group of words/3 words out of 6] Misspelling of the word "мяукают" in the exercises 18

### ISSUE THREAD

**Issue by NatalyChernovaQA** [Brain-up/brn#1870]
Precondition:
Log in with an existing user. Open: Sentences/group of words/3 words out of 6. 17 exercises were completed.
https://brainup.site/groups/2/series/3/subgroup/22/exercise/727/task/727
Steps:
1. Select exercise 18.
2. Press "play".
Actual Result: Written "мАукают"
Expected Result: Correctly "мЯукают".

![18 мАукают](https://user-images.githubusercontent.com/78919128/115923669-3e700100-a487-11eb-8ab5-8546734c959e.jpg)

**Comment by SFin-tech** [comment]
Corrected
