### ISSUE TITLE
WEB UI: implement daily Timer component in the right top corner

### ISSUE THREAD

**Issue by ElenaSpb** [Brain-up/brn#1924]
the timer is about how much time user make exercises in the current day.

see design here 
https://www.figma.com/file/WAn6bQ0qYiOxBDVyXobgpS/Web-BrainUp?node-id=3760%3A2163

current design:

![image](https://user-images.githubusercontent.com/1360552/117990815-31d41f80-b346-11eb-8a56-7a0f4e28d985.png)

expected design:

![image](https://user-images.githubusercontent.com/1360552/117990883-40223b80-b346-11eb-9603-9125e1822425.png)

**Comment by lifeart** [comment]
done
