### ISSUE TITLE
add en translation for index page title + description

### ISSUE THREAD

**Issue by lifeart** [Brain-up/brn#2114]
![telegram-cloud-photo-size-2-5249499700405581335-y](https://user-images.githubusercontent.com/1360552/142859040-fb57becc-4ef0-4898-b072-14946144ea44.jpg)

![image](https://user-images.githubusercontent.com/1360552/142859158-cd447b45-790c-4df4-b31c-f3c669d743f8.png)

**Comment by SFin-tech** [comment]
corrected
