### ISSUE TITLE
Angular: Add detail information about daily statistic

### ISSUE THREAD

**Issue by ElenaSpb** [Brain-up/brn#2232]
I as admin should have possibility to see detail statistic (like a popup or additional window?) when I click on daily column.
https://brainup.site/admin/users/4/statistics 
![image](https://user-images.githubusercontent.com/15213856/173181767-b5eb1abe-6276-415a-8012-4c274312fcbb.png)

Count of done exercises, and count of successfully done from 1 time.
"[Series_Name_A]: N exercises done by J attempts, M successfully from first time.
[Series_Name_B]: K exercises done by G attempts, L successfully from first time."
Example:
Слова Королёвой: 5 упражнений сделано за 7 попыток, 2 успешно с первого раза.

or table

![image](https://user-images.githubusercontent.com/15213856/173181664-fe47e41b-b112-4653-b8cf-dc7187bf30b2.png)

 
![image](https://user-images.githubusercontent.com/15213856/173181730-ee0954bf-04ca-49a2-b569-c34e8d259f79.png)

**Comment by ElenaSpb** [comment]
back for this task: https://github.com/Brain-up/brn/issues/2234

**Comment by ElenaSpb** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ELENA_~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ELENA_~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | Done exercises | Attempts | Sussess   exercises from first time
-- | -- | -- | --
Слова   Королёвой | 5 | 8 | 1



</body>

</html>

**Comment by ElenaSpb** [comment]
+add column please "Listen Words Count" - Количество Прослушанных слов.
because each exercise may have different words count

**Comment by koylubaevnt** [comment]
I added column "Listen Words Count". And make statistics table for selected day
