### ISSUE TITLE
Angular: change default/mock values to real in Users page

### ISSUE THREAD

**Issue by ElenaSpb** [Brain-up/brn#2233]
There should be real values, but we still see mock data
https://brainup.site/admin/users

![image](https://user-images.githubusercontent.com/15213856/173181920-0343e6b1-ff80-4799-b6a7-af325fca3d18.png)

**Comment by ElenaSpb** [comment]
backend: https://github.com/Brain-up/brn/issues/2235

**Comment by ElenaSpb** [comment]
@koylubaevnt something to be done, yes?
so the task is still in progress?
![image](https://user-images.githubusercontent.com/15213856/178953759-1738c4d3-4eda-4a0e-974f-a676a33be16c.png)

**Comment by koylubaevnt** [comment]
No need work. It was fixed on backend  side
