### ISSUE TITLE
BE: add fields in UserWithAnalyticsResponse 

### ISSUE THREAD

**Issue by ElenaSpb** [Brain-up/brn#2235]
BE: change mock to real data in UserWithAnalyticsResponse 

workDayByLastMonth - fill with real data
firstVisit - add and fill
lastVisit - add and fill

**Comment by mironovandrei** [comment]
@ElenaSpb 
I'd like to make sure: firstVisit means time of first login or time when user made his first exercise?

**Comment by ElenaSpb** [comment]
Thank you for contribution!

great start
