### ISSUE TITLE
[UI Web] Add Contact Page with contacts only

### ISSUE THREAD

**Issue by ElenaSpb** [Brain-up/brn#2276]
Contacts for users: 
- Telegram chat for users: https://t.me/BrainUpPlatform 
- In any questions, ideas please write to project email brainupproject@yandex.ru

Contacts for developers:
-  project founder and tech lead in Telegram Elena Moshnikova, https://t.me/ElenaLovesSpb 

![image](https://user-images.githubusercontent.com/15213856/184329323-6f7d41bb-510a-4f47-a7ff-2e2bda50a328.png)

**Comment by LyavonLitvin** [comment]
Frankly says, someone have done allready this issue

**Comment by ElenaSpb** [comment]
Done
Thanks!
