### ISSUE TITLE
[UI Web] Make getting data for Contributors page from Brain-up backend

### ISSUE THREAD

**Issue by ElenaSpb** [Brain-up/brn#2278]
fill page https://brainup.site/contributors auto data from github end-points: 

get Names:  https://docs.github.com/en/rest/users/users#get-a-user

**Comment by koylubaevnt** [comment]
Maybe made loading from our backend? In backend make table wich we will update by scheduler from github and maybe from S3 (for better photo).
UI call contributors to our backend and backend return it to UI
