### ISSUE TITLE
[UI] Add tooltip to Telegram button: Telegram channel for users

### ISSUE THREAD

**Issue by ElenaSpb** [Brain-up/brn#2339]
![image](https://user-images.githubusercontent.com/15213856/195825257-e6befee9-c742-4d09-8a72-dc3d67318bac.png)

**Comment by ViacheslavFin** [comment]
Elena, do you want add tooltip ONLY to Telegram button? Why? You have and other buttons but without tooltips...

**Comment by lifeart** [comment]
@ViacheslavFin as I remember, we have 2 telegram channels, one - for user, and one - for developers

**Comment by ElenaSpb** [comment]
done, thanks!

**Comment by ElenaSpb** [comment]
> @ViacheslavFin as I remember, we have 2 telegram channels, one - for user, and one - for developers

yes!
