### ISSUE TITLE
[UI Ember Bug] Fix signal series

### ISSUE THREAD

**Issue by ElenaSpb** [Brain-up/brn#2389]
example 
https://brainup.site/groups/1/series/7/subgroup/66/exercise/1612/task/signal-task-1

Actual: pronounce text
Expected: pronounce signal

**Comment by HappyEgoiste** [comment]
as of Jan 18, 2023 not fixed, first text is pronounced, and after clicking "Repeat" it says "Undefined".

**Comment by lifeart** [comment]
@HappyEgoiste fixes merged, should be on prod in 30m

**Comment by HappyEgoiste** [comment]
> @HappyEgoiste fixes merged, should be on prod in 30m

Tested, fixed.

**Comment by HappyEgoiste** [comment]
Tested, fixed.
