### ISSUE TITLE
[Web Ember Bug] Overlaying the "timer-wrapper" component and the "Back" (X) button in the exercises

### ISSUE THREAD

**Issue by ViacheslavFin** [Brain-up/brn#2399]
Open https://brainup.site/groups/2/series/1/subgroup/1/exercise/15/task/15
 (for example, 15 exercise)

**Actual result:** Overlaying the "exercise-timer-slot"-"timer-wrapper" component and the "Back" (X) button in the exercise

**Expected result:** No overlay of "timer-wrapper" components and "Back" (X) button in activity
 (Perhaps you need to increase rem (font-size:))

![Наложение  Брайнап](https://user-images.githubusercontent.com/115805175/204133278-0220fed0-4a2f-4215-84c6-5ecc4f2b19d8.PNG)
![Наложение_ Брайнап](https://user-images.githubusercontent.com/115805175/204133841-35126d88-d748-4ee4-b66d-c8680535c643.png)
![Наложение_ Брайнап_](https://user-images.githubusercontent.com/115805175/204133842-51f417ec-7f1b-49d9-8038-9bed34465b88.png)

**Comment by lifeart** [comment]
@ViacheslavFin thank you for report! Fixed

**Comment by ViacheslavFin** [comment]
@lifeart, super!)
