### ISSUE TITLE
[BE] Add new field LastVisit field in https://brainup.fun/admin/users response

### ISSUE THREAD

**Issue by ElenaSpb** [Brain-up/brn#2406]
[BE] AddLast visit field in https://brainup.fun/admin/users response that will be about last visit to our site.
not about last done exercises as it is now. current value from Last Visit move to field Last study activity

![image](https://user-images.githubusercontent.com/15213856/205138394-fdfdc8c9-4a3d-4037-9909-11704db6c840.png)

**Comment by chackomathew** [comment]
@ElenaSpb I'm planning to capture the Last visit in FirebaseTokenAuthenticationFilter.kt after authentication. So the last visit is updated each time request for a user is received.

Do you see any issues with this approach or another better solution?

**Comment by naXa777** [comment]
May I continue from where @chackomathew left off and complete the task?

**Comment by lifeart** [comment]
Hi @naXa777 sure, go on!

**Comment by naXa777** [comment]
I opened new PR #2527 with a solution (back-end part). Please review.

I don't understand this part of the task:

> not about last done exercises as it is now. current value from Last Visit move to field Last study activity

There was no Last Visit field before, or maybe it was removed recently, IDK. @ElenaSpb, please clarify.

**Comment by ElenaSpb** [comment]
Thank you for contribution!
