### ISSUE TITLE
[Bug] Same picture for different syllables "Слоги Королёвой  Гласные А-И-У"

### ISSUE THREAD

**Issue by HappyEgoiste** [Brain-up/brn#2466]
Precondition:

1. Log in as default2 user ([default2@default.ru](mailto:default2@default.ru) / password)

Steps to reproduce:

1. Go to https://brainup.site/groups/1/series/18/subgroup/142/
2. Click on exercises 2, 6, 10, 11, 13, 14, 15, 17, 22 (https://brainup.site/groups/1/series/18/subgroup/142/exercise/1979, https://brainup.site/groups/1/series/18/subgroup/142/exercise/1983, https://brainup.site/groups/1/series/18/subgroup/142/exercise/1987/task/1975, https://brainup.site/groups/1/series/18/subgroup/142/exercise/1988/task/1976, https://brainup.site/groups/1/series/18/subgroup/142/exercise/1990/task/1978, https://brainup.site/groups/1/series/18/subgroup/142/exercise/1991/task/1979, https://brainup.site/groups/1/series/18/subgroup/142/exercise/1992/task/1980, https://brainup.site/groups/1/series/18/subgroup/142/exercise/1994/task/1982, https://brainup.site/groups/1/series/18/subgroup/142/exercise/1999/task/1987

Actual result:
Syllables "ва" and "ву" have the same picture (exercise 2).
Syllables "ма" and "му" have the same picture (exercise 6).
Syllables "фа" and "фу" have the same picture (exercise 10).
Syllables "ка", "ки" and "ку" have the same picture (exercise 11).
Syllables "па" and "пу" have the same picture (exercise 13).
Syllables "ча" and "чу" have the same picture (exercise 14).
Syllables "ща" and "щу" have the same picture (exercise 15).
Syllables "са" and "су" have the same picture (exercise 17).
Syllables "гак" and "гук" have the same picture (exercise 22).

Expected result:
Each syllable has a unique picture

**Comment by ElenaSpb** [comment]
no pictures should be for Syllables 
only for words
