### ISSUE TITLE
[Bug] Incorrect counter of completed exercises on "Слоги Королёвой" main page

### ISSUE THREAD

**Issue by HappyEgoiste** [Brain-up/brn#2467]
Precondition:
1. Log in as an existing user
2. Complete 3 exercises at https://brainup.site/groups/1/series/18/subgroup/142

Steps to reproduce:
1. Go to https://brainup.site/groups/1/series/18
2. Hover the mouse over "[Гласные А-И-У]" to see the number of completed exercises
3. Click on "[Гласные А-И-У]"

Actual result:
The number of actually completed exercises is not the same as in step 2.

Expected result:
The number of actually completed exercises is the same as in step 2.

https://user-images.githubusercontent.com/98885859/215262520-eaed501e-f894-464f-8c07-33bed488b7ce.mp4

**Comment by ElenaSpb** [comment]
the behavior is correct
2 done
available  = done +1
