### ISSUE TITLE
[Bug] No picture for syllables in "Слоги Королёвой Гласные А-И-У"

### ISSUE THREAD

**Issue by HappyEgoiste** [Brain-up/brn#2472]
Precondition:

1. Log in as default2 user ([default2@default.ru](mailto:default2@default.ru) / password)

Steps to reproduce:

1. Go to https://brainup.site/groups/1/series/18/subgroup/142/
2. Click on exercise 18, 19, 20, 27, 28, 31, 33 (https://brainup.site/groups/1/series/18/subgroup/142/exercise/1995/task/1983, https://brainup.site/groups/1/series/18/subgroup/142/exercise/1996/task/1984, https://brainup.site/groups/1/series/18/subgroup/142/exercise/1997/task/1985, https://brainup.site/groups/1/series/18/subgroup/142/exercise/2004/task/1992, https://brainup.site/groups/1/series/18/subgroup/142/exercise/2005/task/1993, https://brainup.site/groups/1/series/18/subgroup/142/exercise/2008/task/1996, https://brainup.site/groups/1/series/18/subgroup/142/exercise/2010/task/1998)

Actual result:
Syllable "зус" does not have a picture (exercise 18)
Syllables "вуф" and "виф" do not have a picture (exercise 19)
Syllables "буп" and "бап" do not have a picture (exercise 20)
Syllables "фаф", "фуф" and "фиф" do not have a picture (exercise 27)
Syllable "кик" does not have a picture (exercise 28)
Syllables "чич" and "чач" do not have a picture (exercise 31)
Syllables "хах", "хух" and "хих" do not have a picture (exercise 33)

Expected result:
Each syllable has a unique picture

**Comment by ElenaSpb** [comment]
no pictures should be for Syllables 
only for words
