### ISSUE TITLE
[Bug] Completed exercises counter is zeroed and exercises are locked after the page is reloaded during solving a task in "Слоги Королёвой О-И-У"

### ISSUE THREAD

**Issue by HappyEgoiste** [Brain-up/brn#2496]
**Precondition:**

Log in as default2 user ([default2@default.ru](mailto:default2@default.ru) / password)

**Steps to reproduce:**

1. Go to https://brainup.site/groups/1/series/18/subgroup/143
2. Complete several exercises from the set
3. Go to next exercise, listen and start solving the task (do not go till the end of the exercise)
4. Reload the page.
5. Close the exercise

**Actual result:**
The user is taken to the exercise group page AND the progress of completed exercises is zeroed, no green ticks on them (see first attachment, 25 exercises have been completed before this happened).
Also (couldn't reproduce, but caught once): all exercise become blocked (see second attachment)

**Expected result:**
The user is taken to the exercise group page AND the progress of completed exercises is NOT zeroed, completed exercises are marked with green ticks.
![Progress zeroed](https://user-images.githubusercontent.com/98885859/224288656-663324b2-f527-49b8-9e45-d6be14e7c5ef.png)
![Locked exercise](https://user-images.githubusercontent.com/98885859/224288649-3a591172-7d99-4f50-b085-b3038c952ec1.png)

**Comment by ElenaSpb** [comment]
![image](https://user-images.githubusercontent.com/15213856/231690829-6f9ac763-f2bb-44f4-8c92-f1e7aa891ff4.png)
current exercise progress does not saved until exercises will not completed

all previous history is saved correctly.

bug is not reproduced
