### ISSUE TITLE
[Bug] A typo in the name of the "Contacts" section in the navbar menu in English version

### ISSUE THREAD

**Issue by Ksenia-Misch** [Brain-up/brn#2516]
**Precondition:**

The home page of the site https://brainup.site/ (English version)  is open

**Steps to reproduce:**

In the main menu of the navigation bar, click the button "More"

**Actual result:**

The menu has a section "Contact"

**Expected Result:**

The menu has a section "Contacts"

**Wednesday:**

Windows 10 
Google Chrome  114.0.5735.199 

![2023-07-23_22-35-50](https://github.com/Brain-up/brn/assets/119502513/6787724b-bdac-4528-9cc3-8da948566847)

**Comment by lifeart** [comment]
fixed in scope of https://github.com/Brain-up/brn/pull/2534
