### ISSUE TITLE
Expired SSL certificate

### ISSUE THREAD

**Issue by naXa777** [Brain-up/brn#2523]
Visit https://brainup.fun/

![image](https://github.com/Brain-up/brn/assets/3858548/5a37d800-ecd7-4bed-a2a1-95c1661159ec)

![image](https://github.com/Brain-up/brn/assets/3858548/4ec062cc-10b1-4f3d-9b71-7a344be69227)

Privacy Error
NET::ERR_CERT_DATE_INVALID

// Friday the 13th is to blame.

**Comment by lifeart** [comment]
@naXa777 thank you for report!
Fixed by https://github.com/Brain-up/brn/commit/1f8c13ad4e591b29177aedad90088a2db9e9bffd
